export const storeProducts = [
  {
    id: 1,
    name: 'Polo homme',
    image: 'img/couch.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 15,
    rating: 4,
    inCart: false,
  },
  {
    id: 2,
    name: 'Chemise homme',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 15,
    rating: 4,
    inCart: false,
  },
  {
    id: 3,
    name: 'Tee Shirt homme',
    image: 'img/couch.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 12,
    rating: 4,
    inCart: false,
  },
  {
    id: 4,
    name: 'Pull homme',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 11,
    rating: 4,
    inCart: false,
  },
]

export const detailProducts = [
  {
    id: 1,
    name: 'Pull homme',
    /* From the public folder in the project */
    image: 'img/logo192.png',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 11,
    rating: 4,
  },
]
