export const products = [
  {
    name: 'Sofa',
    image: 'img/couch.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 15,
    rating: 4,
    inCart: false,
  },
  {
    name: 'Computer',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 15,
    rating: 4,
    inCart: false,
  },
  {
    name: 'Sofa',
    image: 'img/couch.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 12,
    rating: 4,
    inCart: false,
  },
  {
    name: 'Computer',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 11,
    rating: 4,
    inCart: false,
  },
  {
    name: 'Computer',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 11,
    rating: 4,
    inCart: false,
  },
  {
    name: 'Computer',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 11,
    rating: 4,
    inCart: false,
  },
  {
    name: 'Computer',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 11,
    rating: 4,
    inCart: false,
  },
  {
    name: 'Computer',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 11,
    rating: 4,
    inCart: false,
  },
  {
    name: 'Computer',
    image: 'img/computer-4.jpeg',
    description: 'Chemise à rayure homme 100% coton made in Benin.',
    company: 'marcos',
    price: 1,
    countInstock: 10,
    merchantId: 'marcos_fr',
    reviews: [],
    numReviews: 11,
    rating: 4,
    inCart: false,
  },
]
